export interface ChangelogInterface {
    // id is generated by the database
    id?: number,
    app_name?: string,
    type: ChangelogType
    date: string,
    title: string,
    content: string,
    // set by the API
    is_hidden?: boolean
}

export enum ChangelogType {
    BUG = 'BUG',
    FEAT = 'FEAT'
}